import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillFacebook,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">rafi</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Rafi Bin Mahsin
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Entrepreneur
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              In my future I am willing to become a entrepreneur with proving my
              efficiency in business sector.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.facebook.com/MarvellousMahmud"
                target="_blank"
              >
                <AiFillFacebook />
              </a>
              <a
                href="https://www.linkedin.com/in/rafi-md-mahmudul-hasan-423108236/?fbclid=IwAR13mvt9o4xblLNcZclYwmkd4qMCzN-cq-3mXPc0XR5PAO2OoKOQSpCfuhM"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>

              {/* <AiFillYoutube /> */}
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Now, studying at the Department of International Business in OTH
              Amberg- Weiden, Germany. I love to play football, travelling and
              solve rubics cube in my free time. Beside my academic study i like
              to do, Voluntary works, Debating and cycling as extracurricular
              activities.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I can speak English at advance level. And Speak German at primary
              level. In my future I am willing to become a entrepreneur with
              proving my efficiency in business sector.
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
